# typed: false
# frozen_string_literal: true

# SalesPros Companion — Apex language server + MCP/CLI agent channel.
# Generated by apps/companion/scripts/render-brew-formula.sh; do not edit by hand.
class Salespros < Formula
  desc "SalesPros Companion: Apex language server and MCP/CLI agent channel"
  homepage "https://salespros.tools"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.1/salespros-darwin-arm64.tar.gz"
      sha256 "b8bd8ee48d2f32904c6442282c85b8d5142339172d409fd5e6af1f7d516d4a01"
    end
    on_intel do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.1/salespros-darwin-x64.tar.gz"
      sha256 "17a043c88617064666992f2d0ad6fc5fbb350ee9383bc2965436015e02ef2403"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.1/salespros-linux-x64.tar.gz"
      sha256 "933d26ddf9c3c8712855e2c6e8a9e99ce2230cd127b8d91fb1548dad41189132"
    end
  end

  def install
    bin.install "salespros"
    bin.install_symlink bin/"salespros" => "salespros-companion"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/salespros --version")
  end
end
