# typed: false
# frozen_string_literal: true

# SalesPros Companion — Apex language server + MCP/CLI agent channel.
# Generated by apps/companion/scripts/render-brew-formula.sh; do not edit by hand.
class Salespros < Formula
  desc "SalesPros Companion: Apex language server and MCP/CLI agent channel"
  homepage "https://salespros.tools"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.0/salespros-darwin-arm64.tar.gz"
      sha256 "7848d954de4ffbbd810388b9d29a32838f72b59f50e526d6544d9cd358c15249"
    end
    on_intel do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.0/salespros-darwin-x64.tar.gz"
      sha256 "0ea829c2139cc8f93c33a1ac63e9c56b21b0a9d0457acd48dba20f9c94e1372c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salespros-tools/companion/releases/download/v0.1.0/salespros-linux-x64.tar.gz"
      sha256 "2023eb25070857ee70012bb6c24e18636e5a9143a8371e87eefe36df938b080b"
    end
  end

  def install
    bin.install "salespros"
    bin.install_symlink bin/"salespros" => "salespros-companion"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/salespros --version")
  end
end
